services:
  context-coder:
    # build: .
    image: ghcr.io/khromov/context-coder:full
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - COCO_MCP_TRANSPORT=http
    restart: unless-stopped
