services:
  coco-mcp-http:
    # build: .
    image: ghcr.io/khromov/coco:main
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
      - MCP_TRANSPORT=http
    restart: unless-stopped
