services:
  mcp-server:
    # build: .
    image: ghcr.io/khromov/safe-file-mcp:main
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - NODE_ENV=production