# Docker Compose configuration for stdio mode
# This mode is more stable than HTTP/remote mode for direct MCP client integration

services:
  coco:
    # Uncomment to build locally instead of using the pre-built image
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    image: ghcr.io/khromov/coco:main
    
    # Mount the directory you want to work with
    volumes:
      - ./:/app
    
    working_dir: /app
    
    environment:
      - NODE_ENV=production
      - MCP_TRANSPORT=stdio
    
    # Required for stdio mode
    stdin_open: true
    tty: false
    
    # No restart policy for stdio mode - let the MCP client manage lifecycle
    restart: "no"
    
    # Run the container with the stdio transport
    command: ["node", "/opt/mcp-server/dist/index.js", "--stdio"]
