version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "3001:3001"
    volumes:
      # Map local mount directory to container's working directory
      - ./mount:/app
    working_dir: /app
    environment:
      - NODE_ENV=production