name: build + publish all variants

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - name: regular
            build_type: ""
            tags: |
              type=raw,value=main
              type=raw,value=full
            build_args: |
              PUBLIC_HELLO=world
          - name: mini
            build_type: mini
            tags: |
              type=raw,value=main-mini
              type=raw,value=mini
            build_args: |
              BUILD_TYPE=mini
          - name: edit
            build_type: edit
            tags: |
              type=raw,value=main-edit
              type=raw,value=edit
            build_args: |
              BUILD_TYPE=edit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.variant.tags }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image (${{ matrix.variant.name }})
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.variant.build_args }}
